### ISSUE TITLE
Fix and improvements to admin chat command

### ISSUE THREAD

**Issue by paramat** [tenplus1/simple_skins#7]
In your code you had confused 'user' with 'name'. 'name' is the admin using the command, the player the skin is applied to is 'user' which is found from 'param'. So this command only worked in singleplayer giving a skin to yourself. In my code i have used a variable 'playername' to be clear.

I removed the special case for "character_1" as i thought that would cause problems, but maybe for your usage that's needed i don't know.

I added
```
		player:set_properties({
			textures = {skins.skins[playername] .. ".png"},
		})
```
To visually update the skin on command, instead of having to re-enter the world for the skin to visually update.

Finally i send a chat message to the player whose skin has been updated.
```
-- Admin command to set player skin (usually for custom skins)

minetest.register_chatcommand("setskin", {
	params = "<player> <skin number>",
	description = "Admin command to set player skin",
	privs = {server = true},
	func = function(name, param)
		if not param or param == "" then
			return
		end

		local playername, skin = string.match(param, "([^ ]+) (-?%d+)")
		if not playername or not skin then
			return
		end

		skins.skins[playername] = "character_" .. tonumber(skin)
		local player = minetest.get_player_by_name(playername)
		player:set_attribute("skins:skin", skins.skins[playername])
		player:set_properties({
			textures = {skins.skins[playername] .. ".png"},
		})
		minetest.chat_send_player(name,
			playername .. "'s skin set to" .. " character_" .. skin)
		minetest.chat_send_player(playername,
			"Your skin has been set to" .. " character_" .. skin)
	end,
})
```

**Comment by tenplus1** [comment]
Thanks dude, updated :)
